### ISSUE TITLE
xargs: unmatched single quote

### ISSUE THREAD

**Issue by cristobaltapia** [cytopia/docker-bind#14]
I am getting the following error when running the container:

```bash
$ docker-compose up
Creating network "docker-bind_default" with the default driver
Creating docker-bind_bind_1 ... done
Attaching to docker-bind_bind_1
bind_1  | [INFO] Debug level: 1
bind_1  | [INFO] Using default DNS TTL time: 3600 sec
bind_1  | [INFO] Using default DNS Refresh time: 1200 sec
bind_1  | [INFO] Using default DNS Retry time: 180 sec
bind_1  | [INFO] Using default DNS Expiry time: 1209600 sec
bind_1  | [INFO] Using default DNS Max Cache time: 10800 sec
bind_1  | xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
docker-bind_bind_1 exited with code 1
```

I used the following `docker-compose.yml` to run it:

```yml
version: '2'

services:
  bind:
    build: .
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - WILDCARD_DNS='loc=192.168.1.103'

```
